### PR TITLE
Pull in updates from upstream project

### PR DESCRIPTION
**Pull request by busterb**
This includes support for RW memory allocations, automatic 32-bit/64-bit detection, and more.

### CODE REVIEW

**Comment by bwatters-r7** [comment]
Land me

**Comment by Meatballs1** [comment]
Hey @busterb what is the significance of the 64 changes?

**Comment by busterb** [comment]
They are pull requests that were never merged upstream. I addressed the comments inside.

**Comment by OJ** [comment]
Oh good stuff!

**Comment by timwr** [comment]
This was well overdue a merge, apologies if this break something!

**Pull request merged**
